### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by Rapid0nion** [TheDevFromKer/CMS-Attack#1]
Hello, how to disable this feature or what should be in the file http://localhost/proxy.php ?

**Comment by TheDevFromKer** [comment]
Hello. You can change this link to your link where contains proxys, splitted by \n separator

**Comment by Rapid0nion** [comment]
And what if I don’t want to use proxy?

Отправлено с iPhone

**Comment by TheDevFromKer** [comment]
Bad idea. Because using proxy you can simulate real hacker attack to your site. But also you can modify code and remove proxy support.
